### ISSUE TITLE
NoMethodError after rake db:migrate

### ISSUE THREAD

**Issue by christoph88** [micmmakarov/contenteditable#1]
Hi,

I hit a wall after doing a rake db:migrate. I am getting a NoMethodError. Do you have an idea how I can solve this? (sorry I am a newbie)

Thanks!

E:\sl-marketing>rake db:migrate
DL is deprecated, please use Fiddle
rake aborted!
NoMethodError: undefined method `set_table_name' for #<Class:0x5054760>
E:/sl-marketing/config/initializers/locale.rb:1:in`<top (required)>'
E:/sl-marketing/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

**Comment by botisdale** [comment]
See the Rails 3.2.x fix in the readme.
